#program acceping Any Two Values and Swap Them OR Interchange them--Logic-1
#ArithmeticOperatorsEx3.py
a=input("Enter the First Value:")
b=input("Enter the Second Value:")
print("-"*40)
print("Original Values")
print("-"*40)
print("\tOriginal Value of a=",a)
print("\tOriginal Value of b=",b)
print("-"*40)
a,b=b,a # Swapping Logic--Multi Line assginment
print("\tSwapped  Value of a=",a)
print("\tSwapped Value of b=",b)
print("-"*40)